config/routes.rb
Producthunt::Application.routes.draw do
  devise_for :users
  resources :users
  resources :post, only: [:create, :destroy]


  root 'pages#home'
  match '/home', to: 'pages#home', via: 'get'
  match '/help', to: 'pages#help', via: 'get'
  match '/about', to: 'pages#about', via: 'get'
  match '/welcome', to: 'pages#welcome', via: 'get'
  match '/new', to: 'posts#create', via: 'post'  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :description, presence: true, length: { maximum: 60 }
  validates :url, presence:true
  validates :name, presence:true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:coy, :title, :email, :password, :password_confirmation) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

  def about
    
  end

  def welcome
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]

  def index
    
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Post was created"
      redirect_to root_url
    else
      render root_url
    end
  end

  private 
  def post_params
    params.require(:post).permit(:description, :url, :name, :user_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

before_action :configure_permitted_parameters, if: :devise_controller?

private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:coy, :title, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:coy, :title, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
  end

  private
  def signed_in_user
    redirect_to new_user_session_path, alert: "Please sign in." unless signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class_name
    controller.controller_name + "-" + controller.action_name
  end
end
  

app/helpers/date_helper.rb
module DateHelper
  def date_name(date)
    if date == Date.today.strftime("%A %B %d %Y")
      "Today"
    elsif date == Date.yesterday.strftime("%A %B %d %Y")
      "Yesterday"
    else
      Date.parse(date).strftime("%A")
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.coy, class: "gravatar twitter-rounded user-image user-image-as-background")
  end
end
  

app/views/layouts/_header.html.haml
%header.site--header.headroom.headroom--top.headroom--pinned{"data-auto-hide" => "true"}
  .container
    %a.brand{:href => "/"}
      = render 'shared/logo'
      = render 'shared/brand_title'
    .site--header--nav
      %ul.site--header--pages
        %li.site--header--promo
          %span
            %a{:href => "/e/lean-startup-tools"}
              %img{:alt => "Lean startup tools nav", :src => "https://s3.amazonaws.com/ph-s3/list-assets/lean-startup-tools-nav.png"}/
        - unless user_signed_in?
          %li= link_to "Log in", new_user_session_path
        %li= link_to "About", about_path
        %li.site--header--dropdown
          = render 'shared/more_dropdown_menu'
      %ul.site--header--actions
        %li.site--header--post
          %a.new-post-link{:class => (user_signed_in? ? "signed-in" : "")}
        %li.site--header--notifications
          %a.show-notifications{:href => "#"}
      - if user_signed_in?
        .site--header--avatar.site--header--dropdown
          = render 'shared/user_dropdown_menu'

app/views/layouts/_main_head_container.html.haml
.container-main-head.container
  .newsletter-box.well
    %p Get the best new product discoveries in your inbox daily!
    %form#new_subscriber.new_subscriber{"accept-charset" => "UTF-8", :action => "/subscribers", "data-remote" => "true", :method => "post"}
      %div{:style => "display:none"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}/
      %input#subscriber_email.inputfield{:name => "subscriber[email]", :placeholder => "Your email", :type => "email"}/
      %input{:name => "commit", :type => "submit", :value => "Subscribe"}/
  .search-box.search-logged
    .search-form
      .search-field
        %input#q.inputfield{:autocapitalize => "off", :autocomplete => "off", :autocorrect => "off", :placeholder => "Search for products", :spellcheck => "false", :type => "text"}/
      .powered-by{:style => "display: none;"}
        search by
        %a{:href => "http://www.algolia.com/?utm_source=producthunt&utm_medium=link&utm_campaign=producthunt_search", :target => "_blank", :title => "Algolia Realtime Search"}
          %img{:alt => "Algoli Realtime Search", :src => "//www.algolia.com/assets/algolia128x40.png"}/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Product Hunt
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body{:class => body_class_name}
    #close-discussion-panel.close-discussion-body.close-discussion{"data-path" => "/"}
    = render 'shared/login_prompt'
    = render 'shared/post_product'
    = render 'layouts/header'
    = render 'layouts/main_head_container'
    .container-main.container
      %p.notice= notice
      %p.alert= alert
      .yield-container
        = yield

app/views/pages/about.html.haml
.container
  %section
    %h2 What's going on here?
    %p Product Hunt surfaces the best new products, every day. It's a place for product-loving enthusiasts to share and geek out about the latest mobile apps, websites, hardware projects, and tech creations.
    %p
      You can read more about our story on
      = succeed "," do
        %a{:href => "http://pando.com/2013/12/04/can-the-democratic-power-of-a-platform-like-hacker-news-be-applied-to-products/", :target => "_blank"} PandoDaily
      = succeed "," do
        %a{:href => "http://www.fastcolabs.com/3023152/open-company/the-wisdom-of-the-20-minute-startup", :target => "_blank"} Fast Company
      = succeed "," do
        %a{:href => "http://techcrunch.com/2014/06/04/product-hunt-is-the-social-news-site-of-tech-products-read-by-influential-people/", :target => "_blank"} TechCrunch
      = succeed "," do
        %a{:href => "http://thenextweb.com/insider/2014/06/05/product-hunt-is-leveling-the-playing-field-to-help-good-apps-and-startups-get-attention/", :target => "_blank"} The Next Web
      = succeed "," do
        %a{:href => "http://www.businessinsider.com/product-hunt-2014-6", :target => "_blank"} Business Insider
      = succeed "," do
        %a{:href => "http://www.foxbusiness.com/on-air/risk-and-reward/index.html#/v/3639940132001", :target => "_blank"} Fox Business
      = succeed "." do
        %a{:href => "http://www.forbes.com/sites/sethporges/2014/07/03/the-creator-of-product-hunt-spills-the-hit-sites-dirty-details", :target => "_blank"} Forbes
  %section
    %h2 Can I submit a product?
    %p Sure thing! After logging in, click the "Post a Product" link in the header and submit the product's URL, name, and tagline. Each post should include the:
    %ul
      %li URL - Direct link to the product page (avoid links to press or blogs)
      %li Product Name
      %li Tagline - Very short description of the product (make it catchy!)
    %p Here are a few examples:
    %ul
      %li
        %a{:href => "http://mindie.co", :target => "_blank"} Mindie
        \- 7-Second Music Videos
      %li
        %a{:href => "http://www.hatchpet.com/", :target => "_blank"} Hatch
        \- Tamagotchi 2.0
      %li
        %a{:href => "https://www.moveloot.com/", :target => "_blank"} Move Loot
        \- The easiest way to buy and sell used furniture
    %p If the product hasn't been submitted before, it will be queued up for review. Note that not every post will surface on the homepage as hundreds of products are submitted each day and curated by the community.
    %h2 What kind of products do you allow on Product Hunt?
    %p Product Hunt is for sharing new, interesting products. It isn't the place for blog posts, news articles, events, or contract services.
  %section
    %h2 Do you accept submissions for unreleased products?
    %p We encourage people to submit launched products that are available to play with immediately; however, the occasional crowdfunded, pre-launch, or private beta submission is acceptable if it provides thorough information about the product (e.g. explainer video, product feature walkthrough) and proof that it's not vaporware. That said, we may remove pre-launch submissions and recommend founders to wait until their product has launched before submitting.
  %section
    %h2 What about products that have been around a while?
    %p People visit Product Hunt to discover new things. While most submissions should be for new products, occasionally lesser known hunts are equally loved. Since "new" is subjective, we reserve the right to remove submissions that may be well known within the community.
  %section
    %h2 May I post updates for products previously submitted?
    %p Product updates must be substantial, such as the launch of a mobile app or complete product redesign with new functionality, to be considered for resubmission.
  %section
    %h2 How are products ranked?
    %p Every day, new products are submitted and upvoted by the community, ranked by the number of upvotes, time since submission, and other factors.
  %section
    %h2#why-cant-i-comment I really want to join the conversation. Why can't I comment?
    %p Anyone can submit and upvote products; however, Product Hunt isn't prepared to open the discussion to the world. We're working hard to scale the product and team so that more product-loving folks can join the conversation. Meanwhile, we're giving existing members in the community the ability to recommend new members to join.
  %section
    %h2 How do recommendations work?
    %p
      Each week recommendations are awarded to the most engaged and thoughtful contributors based on a variety of factors. Those with recommendations available can invite others to join the conversation by submitting their Twitter username on the
      = succeed "." do
        %a{:href => "http://www.producthunt.com/user/recommendations"} Recommendation page
  %section
    %h2 My product is on Product Hunt. How can I join the discussion?
    %p
      Log in with your personal Twitter account under your name, and
      %a{:href => "https://twitter.com/intent/tweet?text=.%40ProductHunt%2C%20%5Binsert%20your%20product%20name%5D%20is%20on%20Product%20Hunt%20today.%20Can%20I%20have%20commenting%20access%20please%3F%20%5Bplease%20link%20to%20your%20product%20on%20PH%5D", :target => "_blank"} shoot us a tweet at @ProductHunt
      so we can give you access. Once you're in, feel free to briefly introduce yourself in the comments. Pro tip: those that answer questions and actively engage in the discussion (examples
      = succeed "," do
        %a{:href => "http://www.producthunt.com/posts/inside-2-0", :target => "_blank"} here
      = succeed "," do
        %a{:href => "http://www.producthunt.com/posts/sunrise-for-mac", :target => "_blank"} here
      = succeed ")" do
        %a{:href => "http://www.producthunt.com/posts/shadow", :target => "_blank"} here
    %h2 May I ask people to upvote for my product?
    %p Please don’t. People should upvote things they genuinely like or find interesting, not because they were peer pressured to do so. Feel free to spread the word and bring friends into the discussion, but asking or incentivizing people to upvote may trigger the algorithm to drop the product in the ranks or remove it from the front page entirely.
  %section
    %h2 What does the "M" badge represent?
    %p Founders and makers of the product often join the conversation, answering questions and sharing their story. These people are highlighted with a fancy, green "M" badge.
  %section
    %h2 What are Product Hunt exclusives?
    %p
      You may have noticed a golden star next to products featured on the site (
      %a{:href => "http://www.producthunt.com/posts/hatch-3"}> Hatch
      , for example), highlighting exclusive pre-release access or discounts just for product hunters.  If you're launching a product and interested in offering something special to the community, drop us a line at
      %a{:href => "mailto:exclusives@producthunt.com"} exclusives@producthunt.com
  %section
    %h2 Where are my keys?
    %p Sorry but we can't help you with that. You'll have to hunt this down yourself.
  %section
    %h2 Where are the easter eggs!?
    %p
      Well if we straight up told you, it wouldn't really be an easter egg, would it?
      = succeed "." do
        %a{:href => "https://twitter.com/ProductHunt/status/490546158893543425"} Here's a hint
  %section
    %h2 Where can I download brand assets to use on my site or article?
    %p
      If your product was featured on Product Hunt or if you're writing an article about our little piece of the internet, we have vertical and horizontal logos and logo marks in orange, dark gray, and light gray
      %a.brand-assets-link{:href => "https://s3.amazonaws.com/producthunt/ph_brand_assets.zip", :target => "_blank"} available for download.
  %section
    %h2 How can I reach you?
    %p
      Feel free to reach us by email at
      %a{:href => "mailto:hello@producthunt.com", :target => "_blank"} hello@producthunt.com
      or on Twitter (
      %a{:href => "http://twitter.com/producthunt", :target => "_blank"}> @ProductHunt
      ).
  %section
    %h2 Is there a Product Hunt mobile app?
    %p
      You bet! We have a lovely
      %a{:href => "http://www.producthunt.com/apps/ios", :target => "_blank"} iOS app available now
      and plans to release an Android app in the future (sorry, no ETA yet!).
  %section
    %h2 I want to build something rad with Product Hunt. Do you have an API?
    %p
      Not yet but we're getting close! If you're interested in getting early access to the Product Hunt API,
      = succeed "." do
        %a{:href => "https://rrhoover.typeform.com/to/U49PTQ", :target => "_blank"} please submit your information here
  %section
    %h2 I'm hiring. May I advertise on Product Hunt?
    %p
      Absolutely. The Product Hunt audience is global, with talent in marketing, engineering, product management, design, and more. Job opportunities are promoted on the
      %a{:href => "http://www.producthunt.com/jobs", :target => "_blank"} Jobs Board
      in addition to the the email digest. Contact us at
      %a{:href => "mailto:talent@producthunt.com", :target => "_blank"} talent@producthunt.com
      for more information.
  %section
    %h2 Where can I find your Privacy Policy and Terms of Service?
    %p
      For your reading pleasure, review our
      %a{:href => "http://www.producthunt.com/privacy"} Privacy Policy
      and
      = succeed "." do
        %a{:href => "http://www.producthunt.com/tos"} Terms of Service
  %section
    %h2 Who's behind Product Hunt?
    %p
      Product Hunt is crafted with care by
      = succeed "," do
        %a{:href => "https://twitter.com/eriktorenberg", :target => "_blank"} Erik Torenberg
      = succeed "," do
        %a{:href => "http://twitter.com/andreasklinger", :target => "_blank"} Andreas Klinger
      = succeed "," do
        %a{:href => "https://twitter.com/davidkmckinney", :target => "_blank"} David McKinney
      = succeed "," do
        %a{:href => "https://twitter.com/Jonnotie", :target => "_blank"} Jonno Reikwel
      = succeed "," do
        %a{:href => "https://twitter.com/LukasFittl", :target => "_blank"} Lukas Fittl
      = succeed "," do
        %a{:href => "https://twitter.com/NikkiElizDemere", :target => "_blank"} Nichole Elizabeth DeMeré
      = succeed "," do
        %a{:href => "http://twitter.com/rstankov", :target => "_blank"} Radoslav Stankov
      = succeed "," do
        %a{:href => "http://twitter.com/riccardoar", :target => "_blank"} Riccardo Arvizzigno
      %a{:href => "http://ryanhoover.me", :target => "_blank"} Ryan Hoover
      and
      = succeed "." do
        %a{:href => "http://twitter.com/zackshapiro", :target => "_blank"} Zack Shapiro
      %a{:href => "https://rrhoover.typeform.com/to/zdI3DK"} Want to join the team?
    %p
      Special thanks to
      = succeed "," do
        %a{:href => "http://yakshaving.net/", :target => "_blank"} Ash Bhoopathy
      %a{:href => "http://twitter.com/nbashaw", :target => "_blank"} Nathan Bashaw
      and
      %a{:href => "http://twitter.com/shedd", :target => "_blank"} Robert Shedd
      for the help, early on. :grinning:
  %br/
  %a.button{:href => "/"} Back to Product Hunt
  %br/
  %br/
  %br/

app/views/pages/home.html.haml
%div{"data-tooltip-container" => "true", :style => "top: 471px; left: 933px;"}
  .tooltip-content
    .user-hover-card
      %a{:href => "/albn"}
        %img.twitter-rounded.user-image{:alt => "Adxqkzya", :height => "80", :src => "https://pbs.twimg.com/profile_images/518444697321103360/aDxqKZya.jpeg", :width => "80"}/
      %h3 alban
      %h4.user-headline CEO, Sketchfab
      %h4.user-username
        %a{:href => "/albn"} @albn
.posts
  .day.today
    - @posts.each do |day, posts|

      %time.date{:datetime => Date.parse(day)}
        %h4.day-name
        %h4.day-name 
          =date_name(h day)
        =  Date.parse(day).strftime("%B %d")
      %ul.posts-group
        - posts.each do |post|          
          %li.post
            .upvote{"data-id" => post.id, "data-type" => "post"}
              %a.upvote-link{:href => "#"}
              %span.vote-count{"data-id" => post.id} 0
            .url
              =link_to post.name, post.url, :target => "_blank", :class => "post-url title"
              .maker
                %a.maker-badge{:href => "#"}
                .maker-tooltip
                  %span.user-name
                    The maker of this product joined the comments
              %span.post-tagline.description
                = post.description
            %a.view-discussion{"data-id" => post.id, "data-url" => "/posts/takes-io", :href => "/posts/takes-io"}
              =image_tag("/assets/comment.png", :class => "comment-image")
              %p.comment-count 0
            .user-image-holder
              =link_to gravatar_for(post.user, 32), user_path(post.user)
                
              %div{"data-tooltip-container" => "true", :class => "data-tooltip-container"}
                .tooltip-content
                  .user-hover-card
                    =link_to gravatar_for(post.user, 80), user_path(post.user)
                      
                    %h3 
                      = post.user.coy
                    %h4.user-headline 
                      = post.user.title
            %br/

/ %div{"data-tooltip-container" => "true", :class => "data-tooltip-container"}
/   .tooltip-content
/     .user-hover-card
      

app/views/pages/welcome.html.haml
%svg.brand--logo{:height => "30px", :version => "1.1", :viewbox => "0 0 30 30", :width => "30px", :xmlns => "http://www.w3.org/2000/svg", "xmlns:sketch" => "http://www.bohemiancoding.com/sketch/ns", "xmlns:xlink" => "http://www.w3.org/1999/xlink"}
  %g#Page-1{:fill => "none", "fill-rule" => "evenodd", "sketch:type" => "MSPage", :stroke => "none", "stroke-width" => "1"}
    %circle#Oval-1{:cx => "15", :cy => "15", :fill => "#DA552F", :r => "15", "sketch:type" => "MSShapeGroup"}
    %path#P{:d => "M13.944,21 L13.944,17.192 L16.698,17.192 C19.248,17.192 20.642,15.475 20.642,13.435 C20.642,11.378 19.248,9.661 16.698,9.661 L11.02,9.661 L11.02,21 L13.944,21 Z M16.256,14.642 L13.944,14.642 L13.944,12.211 L16.256,12.211 C17.038,12.211 17.667,12.653 17.667,13.435 C17.667,14.2 17.038,14.642 16.256,14.642 Z", :fill => "#FFFFFF", "sketch:type" => "MSShapeGroup"}
%h1.show.show-1.shown Welcome to the Hunt
%p.show.show-2.shown This humble piece of internet was created for product people like you
%p.show.show-3.shown To geek out and discover new, interesting products
%p.show.show-4.shown So without further ado, welcome to the club, and happy hunting :)
.show.show-5.shown
  %h5 Tell us a bit about yourself, then you can join the hunt!
  %form#edit_user_87499.edit_user{"accept-charset" => "UTF-8", :action => "/user/settings/save_welcome", :method => "post"}
    %div{:style => "display:none"}
      %input{:name => "utf8", :type => "hidden", :value => "✓"}/
      %input{:name => "_method", :type => "hidden", :value => "patch"}/
      %input{:name => "authenticity_token", :type => "hidden", :value => "DeelneQivQp5UNZ2u2IHl1jByIXHE4PNa9Qc3+SE39k="}/
    %input#welcome_email_input{:name => "user[email]", :placeholder => "Email address", :type => "email"}/
    %input#user_headline{:maxlength => "40", :name => "user[headline]", :placeholder => "Job title, company name", :size => "40", :type => "text"}/
    %input{:name => "commit", :type => "submit", :value => "Continue"}/
  .tos-and-privacy
    continue if you agreee to our
    %a{:href => "http://www.producthunt.com/tos", :target => "_blank"} Terms
    and
    %a{:href => "http://www.producthunt.com/privacy", :target => "_blank"} Privacy

app/views/posts/new.html.haml
.new-post-modal
  .new-post-wrapper
    .modal-container.new
      .new-post-header
        POST A NEW PRODUCT
      .new-post-subheader
        Find something new and interesting? Hunt it!
      .new-post.well
        %form#new_submission.new_submission{"accept-charset" => "UTF-8", :action => "/submissions", :method => "post"}
          %div{:style => "display:none"}
            %input{:name => "utf8", :type => "hidden", :value => "✓"}/
            %input{:name => "authenticity_token", :type => "hidden", :value => "F7x7j38sVoXyIp1xd71cIVy/R6AOA1UsGE70+rIeJOA="}/
          %input#submission_url.product-url.inputfield{:name => "submission[url]", :placeholder => "Product URL", :type => "url"}/
          %br/
          %input#submission_name.product-name.inputfield{:name => "submission[name]", :placeholder => "Product Name", :type => "text"}/
          %br/
          %input#submission_tagline.product-tagline.inputfield{:name => "submission[tagline]", :placeholder => "Tagline", :type => "text"}/
          %br/
          %input.new_post_submit{"data-loading-text" => "Hunting…", :name => "commit", :type => "submit", :value => "Hunt it"}/

app/views/shared/_brand_title.html.haml
.brand--title
  %h1 Product Hunt
  %h2 The best new products, every day

app/views/shared/_login_prompt.html.haml
.signup-prompt{:style => "display: none;"}
  .modal-bg.close-signup-prompt
  .modal-body
    %h2 Hey there! Please log in before posting a product.
    %a.button{:href => new_user_session_path} Sign in

app/views/shared/_logo.html.haml
%svg.brand--logo{:height => "30px", :version => "1.1", :viewbox => "0 0 30 30", :width => "30px", :xmlns => "http://www.w3.org/2000/svg", "xmlns:sketch" => "http://www.bohemiancoding.com/sketch/ns", "xmlns:xlink" => "http://www.w3.org/1999/xlink"}
  %g#Page-1{:fill => "none", "fill-rule" => "evenodd", "sketch:type" => "MSPage", :stroke => "none", "stroke-width" => "1"}
    %circle#Oval-1{:cx => "15", :cy => "15", :fill => "#DA552F", :r => "15", "sketch:type" => "MSShapeGroup"}
    %path#P{:d => "M13.944,21 L13.944,17.192 L16.698,17.192 C19.248,17.192 20.642,15.475 20.642,13.435 C20.642,11.378 19.248,9.661 16.698,9.661 L11.02,9.661 L11.02,21 L13.944,21 Z M16.256,14.642 L13.944,14.642 L13.944,12.211 L16.256,12.211 C17.038,12.211 17.667,12.653 17.667,13.435 C17.667,14.2 17.038,14.642 16.256,14.642 Z", :fill => "#FFFFFF", "sketch:type" => "MSShapeGroup"}

app/views/shared/_more_dropdown_menu.html.haml
%a{"data-dropdown-trigger" => "more-menu", "data-target" => "#"} More
.dropdown-menu.dropdown-menu-more{"data-dropdown-menu" => "more-menu"}
  %ul.dropdown-menu-list
    %li.dropdown-menu-promo
      %span
        %a{:href => "#"}
          %img{:alt => "Lean startup tools nav", :src => "https://s3.amazonaws.com/ph-s3/list-assets/lean-startup-tools-nav.png"}/
    %li
      %a{:href => "#"} Meetups
    %li
      %a{:href => "#"} Radio
    %li
      %a{:href => "#"} Jobs
    %li
      %a{:href => "#", :target => "_blank"} Blog
    %li
      %a{:href => "#"} App

app/views/shared/_post_product.html.haml
.new-post-modal{:style => "display: none;"}
  .new-post-wrapper
    .modal-container.new
      .new-post-header
        POST A NEW PRODUCT
      .new-post-subheader
        Find something new and interesting? Hunt it!
      .new-post.well
        = form_for :post, :validate => true, url: {action: "create", controller: "/posts"} do |p|
          = p.url_field :url, :required => true, :placeholder => "Product URL"
          = p.text_field :name, :required => true, :placeholder => "Product Name"
          = p.text_field :description, :required => true, :placeholder => "Product Description", :maxlength => 60
          = p.submit "Hunting..."

app/views/shared/_user_dropdown_menu.html.haml
%a{"data-dropdown-trigger" => "user-menu", "data-target" => "#"}= gravatar_for current_user, 32
.dropdown-menu.dropdown-menu-user{"data-dropdown-menu" => "user-menu"}
  %ul.dropdown-menu-list
    %li= link_to "Profile", current_user
    %li
      %a{:href => "#"} Settings
    %li= link_to('Log out', destroy_user_session_path, :method=>'delete')

app/views/users/show.html.haml
.user-heading
  %a{:href => "#"}= gravatar_for @user, 200
  %h2.user-name= @user.coy
  %p.subtitle= @user.title
  %p.join-date
    User ##{@user.id}
.posts
  %ul.posts-group
#showuser_end Hunting down older posts...